### ISSUE TITLE
Installing on arm64

### ISSUE THREAD

**Issue by arhammahajan** [PellelNitram/xournalpp_htr#12]
Hi, before I mention my issue, this project seems wonderful. Hence I am so thrilled to try it out! 
I am currently running fedora on an M1 pro macbook pro using asahi linux. Due to the arm architecture,  it is not possible to run conda(at least not natively). I tried to install the plugin, using the instructions for the cross platform install, but without using a conda environment and was able to get htr_pipeline working.  

I was even able to install the plugin and copied over the files to the plugins/xournalapp_htr folder in the xournalapp config directory, but the plugin does not show up.

**Comment by PellelNitram** [comment]
Hi there @arhammahajan,

thanks for your kind words and the involvement here!!

Were you able to make it run?

If yes, how did you manage to do so? Was the README maybe not clear enough and could be optimised?

If no, do you need my help to solve the issue?

Thanks!! :-)
