### ISSUE TITLE
xournal++ file format

### ISSUE THREAD

**Issue by PUW149** [PellelNitram/xournalpp_htr#2]
The current Xournal++ (1,1,1) saves by default in a format (.xogg) that is not readable by xournalpp_htr, but can 'export as' a readable .xoj file (choose xournal (compatibility)), which is readable by xournalpp_htr.

best, Simon

**Comment by PellelNitram** [comment]
Hi Simon, thanks so much for getting in touch!

I don't quite understand your request :-) What exactly is it that you are asking for?

Are you asking to be able to also read Xournal++ files instead of only Xournal files?

Cheers!

**Comment by PellelNitram** [comment]
Hi there Simon,

previously, only Xournal files were supported. I have now implemented the ability to read native Xournal++ files, see [here](https://github.com/PellelNitram/xournalpp_htr/blob/245bb9f1786349ce9e46beba6ef0ba453dcde41e/xournalpp_htr/documents.py#L114) for reference.

The corresponding Xournal++ plugin, which integrates the HTR process, uses this ability to handle Xournal++ files.

Hence, I am closing this issue :-).

Cheers and thanks for your feedback,
Martin :-)
